apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "azure-k8s-role-assigner.fullname" . }}
  labels:
    {{- include "azure-k8s-role-assigner.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
  {{- if .Values.argocd.enabled }}
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  {{- if .Values.argocd.appProjects.enabled }}
  - apiGroups:
      - argoproj.io
    resources:
      - appprojects
    verbs:
      - get
      - list
      - watch
  {{- end }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "azure-k8s-role-assigner.fullname" . }}
  labels:
    {{- include "azure-k8s-role-assigner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "azure-k8s-role-assigner.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "azure-k8s-role-assigner.fullname" . }}
    namespace: {{ include "azure-k8s-role-assigner.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "azure-k8s-role-assigner.fullname" . }}-leader-election
  namespace: {{ include "azure-k8s-role-assigner.namespace" . }}
  labels:
    {{- include "azure-k8s-role-assigner.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "azure-k8s-role-assigner.fullname" . }}-leader-election
  namespace: {{ include "azure-k8s-role-assigner.namespace" . }}
  labels:
    {{- include "azure-k8s-role-assigner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "azure-k8s-role-assigner.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "azure-k8s-role-assigner.fullname" . }}
    namespace: {{ include "azure-k8s-role-assigner.namespace" . }}
